val:
  _target_: src.datasets.AVSSDataset
  instance_transforms: ${transforms.instance_transforms.inference}
  data_dir: "data/custom"
# test:
#   _target_: src.datasets.AVSSDataset
#   part: "test"
#   instance_transforms: ${transforms.instance_transforms.inference}
