train:
  _target_: src.datasets.AVSSDataset
  part: "train"
  max_audio_length: 20.0
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  part: "val"
  max_audio_length: 20.0
  limit: 2
  instance_transforms: ${transforms.instance_transforms.inference}
