train:
  _target_: src.datasets.AVSSDataset
  part: "train"
  limit: 16
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  part: "val"
  limit: 16
  instance_transforms: ${transforms.instance_transforms.inference}
