defaults:
  - model: sepformer-base
  - metrics: inference
  - datasets: val
  - dataloader: main
  - transforms: example_only_instance
  - _self_
dataloader:
  batch_size: 8
inferencer:
  device_tensors: [
    "mix_audio", "audio_lenght", "targets",
  ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  from_pretrained: "/home/anuiel/Remote/Anuiel/sound-dz-2/dla-hw2/data/weights/dynamix_mixing_checkpoint.pth" # path to the pretrained model
  save_path: null
